title: M090 - Ứng dụng quản lý tài khoản MobiFone toàn diện
description: M090 - Ứng dụng quản lý tài khoản MobiFone toàn diện

author: Tripath Vietnam
email: tudx@tripath.vn

twitter_username: TripathVN
github_username:  TripathVN

markdown: kramdown
theme: minima

source: src/app
destination: dist

permalink: /:title/

exclude: [scss]
keep_files: [css, js, images, vendors]

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap