title: M090 Landing Page
description: M090 Landing Page

author: Tripath Vietnam
email: tudx@tripath.vn

host: localhost

baseurl: "dist"
url: "http://localhost:3000/dist"

twitter_username: jekyllrb
github_username:  jekyll

markdown: kramdown
theme: minima

source: src/app
destination: dist

exclude: [scss]
keep_files: [css, js, images, vendors]

assets:
  sources:
  - _assets/css
  - _assets/fonts
  - _assets/images
  - _assets/js
  - _assets/video

layouts_dir: ./_layouts

plugins:
  - jekyll-feed
  - jekyll-assets